export const data = [
    {
      component: 'Continuous Error Tracking (CET)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Infrastructure as Code Management (IaCM)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Internal Developer Portal (IDP)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Security Testing Orchestration (STO)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Service Reliability Management (SRM)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component:
        'Continuous Integration Enterprise(CIE) - Self Hosted Runners',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    { component: '', date: 'Sep 2024', uptime: '100', cluster: 'Prod Eu1' },
    {
      component: 'Feature Flags (FF)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Custom Dashboards',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Cloud Cost Management (CCM)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Chaos Engineering',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Continuous Delivery - Next Generation (CDNG)',
      date: 'Sep 2024',
      uptime: '100',
      cluster: 'Prod Eu1',
    },
    {
      component: 'Software Supply Chain Assurance (SSCA)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Cloud Cost Management (CCM)',
      date: 'Jun 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Continuous Delivery - Next Generation (CDNG)',
      date: 'Jun 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },

    {
      component: 'Infrastructure as Code Management (IaCM)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Internal Developer Portal (IDP)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Cloud Cost Management (CCM)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Continuous Error Tracking (CET)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Feature Flags (FF)',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    { component: '', date: 'Nov 2023', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Dec 2023', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Jan 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Feb 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Mar 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Apr 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'May 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Jun 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Jul 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Aug 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Sep 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Oct 2024', uptime: '100.00', cluster: 'Prod 1' },
    { component: '', date: 'Nov 2024', uptime: '100.00', cluster: 'Prod 1' },
    {
      component: 'Security Testing Orchestration (STO)',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component:
        'Continuous Integration Enterprise(CIE) - Self Hosted Runners',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Continuous Integration Enterprise(CIE) - Mac Cloud Builds',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component:
        'Continuous Integration Enterprise(CIE) - Windows Cloud Builds',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component:
        'Continuous Integration Enterprise(CIE) - Linux Cloud Builds',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Continuous Delivery - Next Generation (CDNG)',
      date: 'Jul 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
    {
      component: 'Continuous Delivery - Next Generation (CDNG)',
      date: 'Aug 2024',
      uptime: '100.00',
      cluster: 'Prod 1',
    },
  ];
